### ISSUE TITLE
Importer does not send telemetry data to Jaeger if RUST_LOG is not set

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#1388]
I am not sure if this is a bug or a feature, I'll leave that to you guys.

In the past past working on https://issues.redhat.com/browse/TC-2169 I reported that the Importer didn't seem to send data to Jaeger. I discovered that my mistake was that I was not setting the `RUST_LOG=info` and that was the reason of the importer not sending telemetry data.

### How to reproduce it:
- Start the `importer` and do not set `RUST_LOG` at all.
- Connect the importer to opentelemetry following https://github.com/trustification/trustify/blob/main/docs/otel.md or any alternative option available.
- Enable one importer and make it run

Result: See Jaeger UI and you won't see data being sent to Jaeger even if the importer is running.

### Quick reproducible:

Here is a file [demo.zip](https://github.com/user-attachments/files/19069094/demo.zip) that if you unzip it will contain a podman compose yaml file that starts:
- Keycloak
- jaeger
- Prometheus
- Importer
- Server

And connect them all together

My podman compose yaml file contains this part:

```yaml
  trustify-demo-importer:
    image: ghcr.io/trustification/trustd:latest
    environment:
      TRUSTD_DB_HOST: trustify-demo-db
      INFRASTRUCTURE_ENABLED: true
      INFRASTRUCTURE_BIND: "[::]:9010"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://trustify-demo-otel-collector:4317
      OTEL_TRACES_SAMPLER_ARG: "1"
#      RUST_LOG: "debug" // Uncomment this line to make the importer send data to jaeger
```

The last line of my code above can be enabled/disabled for reproducing the issue.

### Workaround

Always make sure the Importer has RUST_LOG=info
