### ISSUE TITLE
ghcr.io/trustification/trustd:0.1.0-alpha.13 does not work

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#671]
Use the following docker compose file to run trustify. It will fail using `docker-compose up`

The error I see is:

```shell
trustify_1  | Error: Connection Error: pool timed out while waiting for an open connection
trustify_1  | Caused by:
trustify_1  |   pool timed out while waiting for an open connection
trustify_1  |   pool timed out while waiting for an open connection
```

Docker Compose:

```yaml
version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  trustify:
    image: ghcr.io/trustification/trustd:0.1.0-alpha.13
    command:
      - 'api'
      - '--devmode'
    ports:
      - "8080:8080"
    environment:
      HTTP_SERVER_BIND_ADDR: 0.0.0.0
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      AUTH_DISABLED: "true"
    depends_on:
      db:
        condition: service_healthy
```
If you use the previous image ghcr.io/trustification/trustd:0.1.0-alpha.12 it will work perfectly fine

> I tried creating container images based on commits of this repo, and the last working version was based on https://github.com/trustification/trustify/commit/11b0edea39573c9ff26d59ec3eca2d6658020354 . I suspect the s3 storage commit that came after it generated the issue, but I wouldn;t bet on it, it was just a 5 minutes testing

**Comment by helio-frota** [comment]
Not a bug :+1: 

Changing the env vars with the [new prefix](https://github.com/trustification/trustify/pull/630) works

```yaml
version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  trustify:
    image: ghcr.io/trustification/trustd:0.1.0-alpha.13
    command:
      - 'api'
      - '--devmode'
    ports:
      - "8080:8080"
    environment:
      HTTP_SERVER_BIND_ADDR: 0.0.0.0
      TRUSTD_DB_USER: myuser
      TRUSTD_DB_PASSWORD: mypassword
      TRUSTD_DB_HOST: db
      TRUSTD_DB_PORT: 5432
      TRUSTD_DB_NAME: mydb
      AUTH_DISABLED: "true"
      RUST_LOG: trace
    depends_on:
      db:
        condition: service_healthy
```

![2024-08-12_15-13](https://github.com/user-attachments/assets/502dcc2b-6a32-425f-b41d-c2f27fbf7b6e)
