### ISSUE TITLE
How to run the container image of trustify without --dev-mode?

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#931]
The compose file below works with `docker-compose up`. However, If I remove the param `--devmode` from the command passed to the trustify container then I get the error:

```
[trustify] | Error: database error: Query Error: error returned from database: relation "importer" does not exist
[trustify] | Caused by:
[trustify] |    Query Error: error returned from database: relation "importer" does not exist
[trustify] |    error returned from database: relation "importer" does not exist
[trustify] |    error returned from database: relation "importer" does not exist
[trustify] |    relation "importer" does not exist
```

```yaml
version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  trustify:
    image: ghcr.io/trustification/trustd:latest
    command:
      - 'api'
      - '--devmode'
    ports:
      - "8080:8080"
    environment:
      HTTP_SERVER_BIND_ADDR: 0.0.0.0
      TRUSTD_DB_USER: myuser
      TRUSTD_DB_PASSWORD: mypassword
      TRUSTD_DB_HOST: db
      TRUSTD_DB_PORT: 5432
      TRUSTD_DB_NAME: mydb
      AUTH_DISABLED: "true"
    depends_on:
      db:
        condition: service_healthy
```

Could I get any advice on what should be the params to be passed to the trustify container in order to make it work? considering I'd like not to pass `--dev-mode` as my intention is to run the container in prod mode and not in dev mode
